# 转推插件配置
[retweet]
version = "0.0.1"
name = "haruno-plugin-retweet"
imageRoot = "/path/to"
url = "twitter_api_url"
  [[retweet.broadcast]]
    account = "123456"
    accounts = ["123456"]
    groupNums = [123456]
